globals:
    simulator-arguments:
        sampling-frequency: 4096
        duration: 4096
        total-duration: 1 day
        start-time: 1577491218
    working-directory: .
    output-directory: output
    metadata-directory: metadata

orchestration:
    population:
        backend: FilePopulationLoader
        source-type: bbh
        n-samples: 1
        arguments:
            path: examples/glitch/gengli/bbh_smoke_population.csv
    signal:
        waveform-model: IMRPhenomXPHM
        minimum-frequency: 2
        detectors:
            - src/gwmock/detector/detectors/E1_Triangle_EMR.interferometer
        output:
            output_directory: signal
            file_name:
                signal-{{ detectors }}-{{ start_time }}-{{ duration }}.gwf
            arguments:
                channel: '{{ detectors }}:STRAIN'
    noise:
        arguments:
            seed: 42
            detectors:
                - E1_triangle_emr
            glitches:
                - kind: gengli_blip
                  rate: 0.0011111111111111111
                  amplitude_distribution:
                      distribution: lognormal
                      mean: 1.0
                      std: 0.0
                  population_file: https://sandbox.zenodo.org/records/413548/files/blip_glitch_population_E1.hdf5
                  psd_file: https://raw.githubusercontent.com/Leuven-Gravity-Institute/gwmock/main/src/gwmock/detector/noise_curves/ET_10_full_cryo_psd.txt
                  low_frequency_cutoff: 5.0
        output:
            output_directory: noise
            file_name: glitch-{{ counter }}.gwf
            arguments:
                channel_prefix: STRAIN
